name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  async: ^2.7.0
  http: ^0.13.3
  dio: ^4.0.0
  webview_flutter: ^2.1.2
  flutter_inappwebview: ^5.3.2
  ffi: ^1.1.1
  json_annotation: ^4.3.0
  flutter_markdown: ^0.6.2
  sqflite: ^2.0.0+3
  get: ^4.3.8
  flutter_local_notifications: ^9.0.3
  rxdart: ^0.27.1
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  geolocator: ^7.7.1
  share: ^2.0.4
  equatable: ^2.0.2
  protobuf: ^2.0.0
  grpc: ^3.0.2
  flutter_js: 0.5.0+0
  carousel_slider: ^4.0.0
  fl_chart: ^0.36.2
  font_awesome_flutter: ^10.0.0-beta
  flutter_svg: ^0.23.0+1
  flutter_swiper: ^1.1.6
  introduction_screen: ^2.1.0
  image_picker: ^0.8.4+4
  file_picker: ^4.2.1
  #image: ^3.0.2
  #photo_view: ^0.12.0
  #cached_network_image: ^3.1.0
  extended_image: ^5.1.3
  extended_text_library: ^7.0.0
  flutter_cache_manager: ^3.1.2
  syncfusion_flutter_charts: ^19.2.48
  camera: ^0.9.4+3
  qr_flutter: ^4.0.0
  video_player: ^2.1.10
  animations: ^2.0.1
  hive: ^2.0.4
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  shimmer: ^2.0.0
  permission_handler: ^8.1.3
  args: ^2.1.1
  animate_do: ^2.0.0
  getwidget: ^2.0.3
  vector_math: ^2.1.0
  shelf_proxy: ^1.0.1
  shelf_static: ^1.1.0
# provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.17.10
  pigeon: ^1.0.6
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  protoc_plugin: ^20.0.0
  dart_style: ^2.2.0
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.0

dependency_overrides:
  test: ^1.17.10
  async: ^2.6.1
  dart_style: ^2.1.1
  args: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/dist/
    - assets/dist/css/
    - assets/dist/js/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.jpg"